/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalorimanager.ui;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;
import javax.swing.JOptionPane;
import kalorimanager.util.I18n;
import kalorimanager.util.CryptoUtil;
import kalorimanager.util.MongoUtil;
import org.bson.Document;
import kalorimanager.ui.RegisterFrame;

/**
 *
 * @author ASUS
 */
public class LoginFrame extends javax.swing.JFrame {

    public LoginFrame() {
        initComponents();
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLoginActionPerformed(evt);
        }
    });
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRegisterActionPerformed(evt);
        }
    });
        setLocationRelativeTo(null);
        initLanguageComboBox();
        updateTexts();
    }
    
    private void registerUser() {
        new RegisterFrame().setVisible(true);
    }

    
    private void initLanguageComboBox() {
    if (ComboBahasa != null) {
        // Hapus listener sementara
        ActionListener[] listeners = ComboBahasa.getActionListeners();
        for (ActionListener listener : listeners) {
            ComboBahasa.removeActionListener(listener);
        }

        ComboBahasa.removeAllItems();
        ComboBahasa.addItem("EN");
        ComboBahasa.addItem("ID");
        ComboBahasa.setSelectedItem("EN");

        // Tambahkan kembali listener
        for (ActionListener listener : listeners) {
            ComboBahasa.addActionListener(listener);
        }
    }
}

    private void updateTexts() {
        lblUsername.setText(I18n.get("username") + ":");
        lblPassword.setText(I18n.get("password") + ":");
        btnLogin.setText(I18n.get("login"));
        btnRegister.setText(I18n.get("register"));
        setTitle("KaloriManager - " + I18n.get("login"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        ComboBahasa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        lblUsername.setText("Username : ");

        lblPassword.setText("Password : ");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(204, 204, 255));
        btnLogin.setText("Login");

        btnRegister.setBackground(new java.awt.Color(204, 204, 255));
        btnRegister.setText("Register");

        ComboBahasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBahasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBahasaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnLogin)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegister)
                                .addGap(57, 57, 57)))))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ComboBahasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ComboBahasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnRegister))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUsername.getText().trim();
        String password = txtPassword.getText();

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, I18n.get("register_validation_empty"), I18n.get("error"), JOptionPane.ERROR_MESSAGE);
            return;
        }

        Document doc = MongoUtil.getDB().getCollection("users")
                .find(new Document("username", username)).first();

        if (doc == null) {
            JOptionPane.showMessageDialog(this, I18n.get("user_not_found"), I18n.get("error"), JOptionPane.ERROR_MESSAGE);
            return;
        }

        String hash = doc.getString("passwordHash");
        if (CryptoUtil.checkPassword(password, hash)) {
            JOptionPane.showMessageDialog(this, I18n.get("login_success"), I18n.get("success"), JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new MainFrame(username).setVisible(true);  // ← Buka MainFrame dengan username
        } else {
            JOptionPane.showMessageDialog(this, I18n.get("wrong_password"), I18n.get("error"), JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        this.dispose(); // Menutup LoginFrame
        registerUser();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    private void btnSwitchLangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchLangActionPerformed

    }//GEN-LAST:event_btnSwitchLangActionPerformed

    private void ComboBahasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBahasaActionPerformed
        try {
        String selected = (String) ComboBahasa.getSelectedItem();
        if (selected != null) {
            String langCode = selected.equals("ID") ? "id" : "en";
            I18n.setLanguage(langCode);
            updateTexts();
        }
        } catch (Exception e) {
            System.err.println("Error mengubah bahasa: " + e.getMessage());
            // Fallback ke bahasa Inggris
            I18n.setLanguage("en");
        }
    }//GEN-LAST:event_ComboBahasaActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBahasa;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}